 ### <span style="color:red">**Enter your name and person number here:**</span> 
 
 # Cortlandt Chin 5022-8454

### Execute the cell below before proceeding.

The code in this cell will download a couple files with Python scripts from the Internet. Make sure that you have a network connection before executing it.  

In [1]:
import requests
with open("hill_cipher_extra_credit.py", 'w') as foo:
    foo.write(requests.get("https://git.io/JenzP").text)
with open("hill_cipher_extra_credit_samples.py", 'w') as foo:
    foo.write(requests.get("https://git.io/JenzX").text)
from hill_cipher_extra_credit import *

# Extra credit Hill cipher


## Instructions

* This is an extra credit exercise, you are not required to submit it.
* The correct solution will give you an extra 10% of your Exam 1 score (e.g if your exam score will be
  80 points and you complete this assignment, you will receive extra 8 points).
* There is no partial credit on this assignment. Incomplete solutions (e.g. incorrect decoding of the cipher, printing the decoded message without any computations  etc.) will receive no credit.
* The whole assignment must be completed within this notebook. Computations done on paper or using some other program will not be graded.
* Once you complete this assignment, upload this notebook file to UBLearns. The name of this notebook file is `hill_cipher_extra_credit.ipynb`. You can execute the command `pwd` in a code cell of this notebook to check where this file is located on your computer. 
* The submission deadline is **Saturday, October 5, 11:59 PM**. 

**Note:** The functions `char2num()` and `num2char()` should be helpful with this exercise. `char2num()` converts capital letters into numbers:

In [2]:
char2num("ABCDEF")

[1, 2, 3, 4, 5, 6]

Conversely, `num2char()` converts a list of numbers into corresponding characters. It also displays a black block for each number on the list that does not correspond to any character:

In [3]:
mylist = [20,8,9,19,0,9,19,0,1,0,20,5,19,20, 100, -1]
num2char(mylist)

  20   8   9  19   0   9  19   0   1   0  20   5  19  20 100  -1
   T   H   I   S   _   I   S   _   A   _   T   E   S   T   #   #



The function `num2char_text_only()` is similar, but it prints only characters, without the corresponding numbers:

In [4]:
mylist = [20,8,9,19,0,9,19,0,1,0,20,5,19,20, 100, -1]
num2char_text_only(mylist)

'THIS_IS_A_TEST##'

----

### Extra Credit Exercise

In the next cell enter your UB person number (digits only, no spaces, dashes etc.) assigning it to the variable `pnum`, and execute the cell. For example, if your UB person number is 50201234, then the next cell should be `pnum = 50201234`

In [5]:
pnum = 50228454

Execute the next cell to produce a message encrypted with the Hill cipher cipher:

In [6]:
cipher = cipher_generator(pnum)
cipher

[125, 99, 91, 100, 93, 50, 139, 110, 101, 81, 77, 37, 147, 115, 110, 172, 172,
 65, 100, 104, 31, 134, 152, 21, 144, 109, 113, 176, 162, 91, 30, 32, 8, 188, 
200, 51, 68, 60, 39, 166, 165, 64, 167, 147, 97]

The message starts with the word "CONFIDENTIAL". Decrypt the message.

### Solution:

We are assuming the encryption key is a 3 $\times$ 3 matrix. Therefore we shall count the number of entries in `cipher` and split it so that each vector $u_{i} \in$ $\mathbb{R}^{3}$, with $i = [1,15]$

In [7]:
len(cipher) #counts the number of entries in the cipher

45

In [8]:
u1 = Matrix(cipher[:3])  # a vector consisting of the first 3 numbers of the encrypted message
u2 = Matrix(cipher[3:6]) # a vector consisting of the next 3 numbers of the encrypted message
u3 = Matrix(cipher[6:9]) # and so on...
u4 = Matrix(cipher[9:12])
u5 = Matrix(cipher[12:15])
u6 = Matrix(cipher[15:18])
u7 = Matrix(cipher[18:21])
u8 = Matrix(cipher[21:24])
u9 = Matrix(cipher[24:27])
u10 = Matrix(cipher[27:30])
u11 = Matrix(cipher[30:33])
u12 = Matrix(cipher[33:36])
u13 = Matrix(cipher[36:39])
u14 = Matrix(cipher[39:42])
u15 = Matrix(cipher[42:45])

u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15 #spits out separated 15 vectors 

⎛⎡125⎤  ⎡100⎤  ⎡139⎤  ⎡81⎤  ⎡147⎤  ⎡172⎤  ⎡100⎤  ⎡134⎤  ⎡144⎤  ⎡176⎤  ⎡30⎤  ⎡1
⎜⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢ 
⎜⎢99 ⎥, ⎢93 ⎥, ⎢110⎥, ⎢77⎥, ⎢115⎥, ⎢172⎥, ⎢104⎥, ⎢152⎥, ⎢109⎥, ⎢162⎥, ⎢32⎥, ⎢2
⎜⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢ 
⎝⎣91 ⎦  ⎣50 ⎦  ⎣101⎦  ⎣37⎦  ⎣110⎦  ⎣65 ⎦  ⎣31 ⎦  ⎣21 ⎦  ⎣113⎦  ⎣91 ⎦  ⎣8 ⎦  ⎣5

88⎤  ⎡68⎤  ⎡166⎤  ⎡167⎤⎞
  ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥⎟
00⎥, ⎢60⎥, ⎢165⎥, ⎢147⎥⎟
  ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥⎟
1 ⎦  ⎣39⎦  ⎣64 ⎦  ⎣97 ⎦⎠

Next logical step would be to multiply $A^{-1}$ with each $u_{i}$, with $A^{-1}$ being the inverse of the encryption key $A$. The only problem is that neither the encryption nor the decryption key is not given.

 However, we are given the first 12 letters of the encrypted message, which is "CONFIDENTIAL". The assumption is that this will help us find the encryption key.

We will attempt to verify this assumption by executing `char2num()` on "CONFIDENTIAL" and splitting it into vectors.

In [9]:
text = "CONFIDENTIAL"
len(text)

12

In [10]:
char2num(text)

[3, 15, 14, 6, 9, 4, 5, 14, 20, 9, 1, 12]

In [11]:
v1 = Matrix(Out[10][:3])  
v2 = Matrix(Out[10][3:6]) 
v3 = Matrix(Out[10][6:9]) 
v4 = Matrix(Out[10][9:12])

v1, v2, v3, v4

⎛⎡3 ⎤  ⎡6⎤  ⎡5 ⎤  ⎡9 ⎤⎞
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎟
⎜⎢15⎥, ⎢9⎥, ⎢14⎥, ⎢1 ⎥⎟
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥⎟
⎝⎣14⎦  ⎣4⎦  ⎣20⎦  ⎣12⎦⎠

We are assuming that $T\colon \mathbb{R}^3 \rightarrow \mathbb{R}^3$ is a linear transformation such that $\mathbf{v}_{1} = T(\mathbf{u}_{1})$ Meaning that $\begin{bmatrix} 3 \\ 15 \\ 14 \end{bmatrix}$, which are the first 3 numbers that correspond to CON, somehow maps to $\begin{bmatrix} 125 \\ 99 \\ 91 \end{bmatrix}$.

Therefore, we need to find $T$, which is the encryption matrix $A$. After we find $A$, we shall test it for invertibility. This will at least indicate whether or not we are in the right direction. If $A$ if invertible, we shall compute $A^{-1}$ to give us the decryption key.

We need to find a 3 x 3 matrix such that it can multiply to $\mathbf{u}$ to give us the decryption key. If $\mathbf{u}$ is the matrix for the first 12 letters of "CONFIDENTIAL", then $\mathbf{u}$ would be $T(\mathbf{v})$, the first 12 letters after the transformation. Therefore, we should perform matrix multiplication to give us the encryption key $A$. 

Note that "CONFIDENTIAL" is 12 letters long, and the $3 x 3$ matrix we seek contains 9 entries by definition. Because of this, we will chop the last 3 letters of "CONFIDENTIAL" so that it spells "CONFIDENT". So by construction, $$\mathbf{v} = \begin{bmatrix} 3 & 6 & 5 \\ 15 & 9 & 14 \\ 14 & 4 & 20 \end{bmatrix},\hspace{.5cm} T(\mathbf{v}) = \mathbf{u} = \begin{bmatrix} 125 & 100 & 139 \\ 99 & 93 & 110 \\ 91 & 50 & 101 \end{bmatrix}$$  

In order to determine what we're multiplying, we need to do some algebriac manipulation. Observe.

Let $\mathbf{v} = \begin{bmatrix} 3 & 6 & 5 \\ 15 & 9 & 14 \\ 14 & 4 & 20 \end{bmatrix}$ and $\mathbf{u} = \begin{bmatrix} 125 & 100 & 139 \\ 99 & 93 & 110 \\ 91 & 50 & 101 \end{bmatrix}$

If $A\mathbf{x} = b$, then $A\mathbf{v} = \mathbf{u}$ 

$$A\mathbf{v} = \mathbf{u}$$ 

$$A(\mathbf{v}\times\mathbf{v}^{-1}) = \mathbf{u}\times\mathbf{v}^{-1}$$  

$$\therefore A = \mathbf{u}\times \mathbf{v}^{-1}$$ 

According to our derivation, we need to calculate $\mathbf{u}$ times the inverse of $\mathbf{v}$ (or $\mathbf{v^{-1}}$), to give us the encryption key $A$ 

In [12]:
v = Matrix([[3,6,5],[15,9,14],[14,4,20]]) # `char2num()` for "CONFIDENT" matrix
u = Matrix([[125,100,139],[99,93,110],[91,50,101]]) #"CONFIDENT" after transformation matrix
v,u

⎛⎡3   6  5 ⎤  ⎡125  100  139⎤⎞
⎜⎢         ⎥  ⎢             ⎥⎟
⎜⎢15  9  14⎥, ⎢99   93   110⎥⎟
⎜⎢         ⎥  ⎢             ⎥⎟
⎝⎣14  4  20⎦  ⎣91   50   101⎦⎠

In [13]:
v**-1 #inverse of v

⎡-62     50   -13 ⎤
⎢────   ───   ────⎥
⎢291    291   194 ⎥
⎢                 ⎥
⎢ 52          -11 ⎥
⎢───   5/291  ────⎥
⎢291          194 ⎥
⎢                 ⎥
⎢ 11   -12     21 ⎥
⎢ ──   ────   ─── ⎥
⎣ 97    97    194 ⎦

In [14]:
u * v**-1 #Possible encryption key

⎡7  6  1⎤
⎢       ⎥
⎢8  5  0⎥
⎢       ⎥
⎣1  4  2⎦

In [15]:
Out[14]**-1 #Therefore possible decryption key

⎡10   -8   -5 ⎤
⎢             ⎥
⎢-16  13    8 ⎥
⎢             ⎥
⎣27   -22  -13⎦

In [16]:
D = Matrix([[7,6,1],[8,5,0],[1,4,2]]) #encryption key
De = Matrix([[10,-8,-5],[-16,13,8],[27,-22,-13]]) #decryption key

D,De #(encryption key), (decryption key)

⎛⎡7  6  1⎤  ⎡10   -8   -5 ⎤⎞
⎜⎢       ⎥  ⎢             ⎥⎟
⎜⎢8  5  0⎥, ⎢-16  13    8 ⎥⎟
⎜⎢       ⎥  ⎢             ⎥⎟
⎝⎣1  4  2⎦  ⎣27   -22  -13⎦⎠

Verifying the encryption key: 

In [17]:
D*v1

⎡125⎤
⎢   ⎥
⎢99 ⎥
⎢   ⎥
⎣91 ⎦

The encryption key is therefore valid because $\mathbf{v}_{1} = \begin{bmatrix} 3 \\ 15\\ 14 \end{bmatrix} \rightarrow \mathbf{u}_{1} = \begin{bmatrix} 125 \\ 99 \\ 91 \end{bmatrix}$

Computing $A = \mathbf{u}\times\mathbf{v}^{-1}$ for each vectors:

In [18]:
A1 = De*u1
A2 = De*u2
A3 = De*u3
A4 = De*u4
A5 = De*u5
A6 = De*u6
A7 = De*u7
A8 = De*u8
A9 = De*u9
A10 = De*u10
A11 = De*u11
A12 = De*u12
A13 = De*u13
A14 = De*u14
A15 = De*u15

A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15

⎛⎡3 ⎤  ⎡6⎤  ⎡5 ⎤  ⎡9 ⎤  ⎡0 ⎤  ⎡19⎤  ⎡13⎤  ⎡19⎤  ⎡3 ⎤  ⎡9 ⎤  ⎡4⎤  ⎡25⎤  ⎡5⎤  ⎡2
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢ ⎥  ⎢ 
⎜⎢15⎥, ⎢9⎥, ⎢14⎥, ⎢1 ⎥, ⎢23⎥, ⎢4 ⎥, ⎢0 ⎥, ⎢0 ⎥, ⎢17⎥, ⎢18⎥, ⎢0⎥, ⎢0 ⎥, ⎢4⎥, ⎢1
⎜⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢  ⎥  ⎢ ⎥  ⎢  ⎥  ⎢ ⎥  ⎢ 
⎝⎣14⎦  ⎣4⎦  ⎣20⎦  ⎣12⎦  ⎣9 ⎦  ⎣15⎦  ⎣9 ⎦  ⎣1 ⎦  ⎣21⎦  ⎣5 ⎦  ⎣2⎦  ⎣13⎦  ⎣9⎦  ⎣2

0⎤  ⎡9 ⎤⎞
 ⎥  ⎢  ⎥⎟
 ⎥, ⎢15⎥⎟
 ⎥  ⎢  ⎥⎟
0⎦  ⎣14⎦⎠

In [19]:
u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15 #used for cross-checking

⎛⎡125⎤  ⎡100⎤  ⎡139⎤  ⎡81⎤  ⎡147⎤  ⎡172⎤  ⎡100⎤  ⎡134⎤  ⎡144⎤  ⎡176⎤  ⎡30⎤  ⎡1
⎜⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢ 
⎜⎢99 ⎥, ⎢93 ⎥, ⎢110⎥, ⎢77⎥, ⎢115⎥, ⎢172⎥, ⎢104⎥, ⎢152⎥, ⎢109⎥, ⎢162⎥, ⎢32⎥, ⎢2
⎜⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢   ⎥  ⎢  ⎥  ⎢ 
⎝⎣91 ⎦  ⎣50 ⎦  ⎣101⎦  ⎣37⎦  ⎣110⎦  ⎣65 ⎦  ⎣31 ⎦  ⎣21 ⎦  ⎣113⎦  ⎣91 ⎦  ⎣8 ⎦  ⎣5

88⎤  ⎡68⎤  ⎡166⎤  ⎡167⎤⎞
  ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥⎟
00⎥, ⎢60⎥, ⎢165⎥, ⎢147⎥⎟
  ⎥  ⎢  ⎥  ⎢   ⎥  ⎢   ⎥⎟
1 ⎦  ⎣39⎦  ⎣64 ⎦  ⎣97 ⎦⎠

In [20]:
numbers = list(Matrix([A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15])) #converting the matrix to a list
numbers

[3, 15, 14, 6, 9, 4, 5, 14, 20, 9, 1, 12, 0, 23, 9, 19, 4, 15, 13, 0, 9, 19, 0
, 1, 3, 17, 21, 9, 18, 5, 4, 0, 2, 25, 0, 13, 5, 4, 9, 20, 1, 20, 9, 15, 14]

Converting numbers to letters: 

In [21]:
num2char(numbers)

   3  15  14   6   9   4   5  14  20   9   1  12   0  23   9  19   4  15  13   0
   C   O   N   F   I   D   E   N   T   I   A   L   _   W   I   S   D   O   M   _

   9  19   0   1   3  17  21   9  18   5   4   0   2  25   0  13   5   4   9  20
   I   S   _   A   C   Q   U   I   R   E   D   _   B   Y   _   M   E   D   I   T

   1  20   9  15  14
   A   T   I   O   N



In [22]:
print("The message is:")
num2char_text_only(numbers)

The message is:


'CONFIDENTIAL_WISDOM_IS_ACQUIRED_BY_MEDITATION'

$\hspace{10in} \blacksquare$